### ISSUE TITLE
graphql error results in blank page

### ISSUE THREAD

**Issue by erkannt** [libero/reviewer#1164]
To repro in umbrella:

- `make start_master_localhost`
- create a submission
- `make stop`
- `make start_master_localhost`
- go to localhost:9000

Now there is a valid token but the database doesn't now about the user. This leads to /graphql responding with errors upon the `GetSubmissions` and `GetCurrentUser` call, resulting in the page going blank.

```
{"errors":[{"message":"Undefined binding(s) detected when compiling SELECT. Undefined column(s): [created_by] query: select \"id\", \"created\", \"updated\", \"created_by\", \"status\", \"meta\", \"cover_letter\", \"previously_discussed\", \"previously_submitted\", \"cosubmission\", \"opposed_senior_editors_reason\", \"opposed_reviewing_editors_reason\", \"opposed_reviewers_reason\", \"last_step_visited\", \"submitter_signature\", \"disclosure_consent\" from \"public\".\"manuscript\" where \"created_by\" = ?","locations":[{"line":2,"column":3}],"path":["getSubmissions"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["Error: Undefined binding(s) detected when compiling SELECT. Undefined column(s): [created_by] query: select \"id\", \"created\", \"updated\", \"created_by\", \"status\", \"meta\", \"cover_letter\", \"previously_discussed\", \"previously_submitted\", \"cosubmission\", \"opposed_senior_editors_reason\", \"opposed_reviewing_editors_reason\", \"opposed_reviewers_reason\", \"last_step_visited\", \"submitter_signature\", \"disclosure_consent\" from \"public\".\"manuscript\" where \"created_by\" = ?","    at QueryCompiler_PG.toSQL (/app/node_modules/knex/lib/query/compiler.js:101:13)","    at Builder.toSQL (/app/node_modules/knex/lib/query/builder.js:77:44)","    at /app/node_modules/knex/lib/runner.js:30:36","    at /app/node_modules/knex/lib/runner.js:253:24","    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)","    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)","    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)","    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)","    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)","    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)","    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)","    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)","    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:15:14)","    at processImmediate (internal/timers.js:456:21)","    at process.topLevelDomainCallback (domain.js:137:15)"]}}}]}
```
```
{"errors":[{"message":"Cannot return null for non-nullable field User.id.","locations":[{"line":3,"column":5}],"path":["getCurrentUser","id"],"extensions":{"code":"INTERNAL_SERVER_ERROR","exception":{"stacktrace":["Error: Cannot return null for non-nullable field User.id.","    at completeValue (/app/node_modules/graphql/execution/execute.js:560:13)","    at completeValueCatchingError (/app/node_modules/graphql/execution/execute.js:495:19)","    at resolveField (/app/node_modules/graphql/execution/execute.js:435:10)","    at executeFields (/app/node_modules/graphql/execution/execute.js:275:18)","    at collectAndExecuteSubfields (/app/node_modules/graphql/execution/execute.js:713:10)","    at completeObjectValue (/app/node_modules/graphql/execution/execute.js:703:10)","    at completeValue (/app/node_modules/graphql/execution/execute.js:591:12)","    at completeValue (/app/node_modules/graphql/execution/execute.js:557:21)","    at /app/node_modules/graphql/execution/execute.js:492:16","    at processTicksAndRejections (internal/process/task_queues.js:97:5)","    at async Promise.all (index 0)"]}}}]}
```

This specific bug doesn't need to be fixed, as we shouldn't lose the db in prod. But we need to give the user something nicer than a blank page if our backend breaks with a similar error.

**Comment by erkannt** [comment]
after discussion with @hdrury1 @norisalsaadie will raise issues to add error handling in favour of this issue.
