### ISSUE TITLE
Error during submission shows warning but lets me proceed

### ISSUE THREAD

**Issue by erkannt** [libero/reviewer#1198]
Error in sftp upload leads to the read banner being shown but I still get shown the survey and get told that the submission has been sent to eLife.

I'm also not told how or whom to contact.

![Screenshot_2020-07-23 eLife](https://user-images.githubusercontent.com/19282025/88289606-67dbe080-cced-11ea-888d-30a81b49548b.png)

Backend Error:

```
{"level":30,"time":1595509262557,"pid":1,"hostname":"libero-reviewer--stg-submission-845488bcb9-6xqb9","service":"reviewer-submission","realm":"infra","msg":"resolver: saveDisclosurePage(e5146ae5-5114-4046-95bd-ca922f2b2597)","v":1}
{"level":50,"time":1595509262617,"pid":1,"hostname":"libero-reviewer--stg-submission-845488bcb9-6xqb9","service":"reviewer-submission","realm":"infra","msg":"User not allowed to submit Error: User not allowed to submit\n    at WizardService.saveDisclosurePage (/app/dist/application/wizard/service.js:68:19)","v":1}
(node:1) UnhandledPromiseRejectionWarning: Error: connect: client-socket error. Address lookup failed for host sftp.ejpress.com
 after 2 attempts
    at Object.formatError (/app/node_modules/ssh2-sftp-client/src/utils.js:62:18)
    at Client.connectErrorListener (/app/node_modules/ssh2-sftp-client/src/index.js:98:21)
    at Object.onceWrapper (events.js:417:26)
    at Client.emit (events.js:310:20)
    at Client.EventEmitter.emit (domain.js:482:12)
    at Socket.<anonymous> (/app/node_modules/ssh2/lib/client.js:307:10)
    at Socket.emit (events.js:310:20)
    at Socket.EventEmitter.emit (domain.js:482:12)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
(node:1) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)

```

**Comment by erkannt** [comment]
Underlying sftp issue resolved #1199
