### ISSUE TITLE
Fix Staging

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#685]
Staging is red see https://alfred.elifesciences.org/job/test-libero-reviewer/

**Comment by diversemix** [comment]
Looking at the logs:
```
$ kubectl logs libero-reviewer--staging-submission-6d5c7b6d65-4k5d9
internal/fs/utils.js:220
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/etc/reviewer/config.client.json'
    at Object.openSync (fs.js:440:3)
    at Object.readFileSync (fs.js:342:35)
    at Object.<anonymous> (/app/dist/config.js:9:38)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/app/dist/main.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1043:10)
    at internal/main/run_main_module.js:17:11 {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/etc/reviewer/config.client.json'
```

**Comment by erkannt** [comment]
This looks like the issue @erezmus and I were looking at yesterday. I think he found that it was a  config file naming issue. The error message mentions `config.client.json` but the templates in reviewer-config and the `configmap` in `helm/libero-reviewer/templates` use `config.public.json`.

I can dive into this on Thursday.

**Comment by diversemix** [comment]
All looks good on the last build:
```

Run docker load -i docker-image/reviewer-submission.tar
Loaded image: libero/reviewer-submission:0961e5026d93e2091f892adf7dc92611f1bcdb1e
Loaded image: libero/reviewer-xpub-postgres:0961e5026d93e2091f892adf7dc92611f1bcdb1e
psql: could not connect to server: No such file or directory
	Is the server running locally and accepting
	connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
if [ ! -e ./config/config.json ] ; then cp config/config.example.json config/config.json ; fi
if [ ! -e ./config/config.local.json ] ; then cp config/config.local.example.json config/config.local.json ; fi
if [ ! -e ./config/config.client.json ] ; then cp config/config.client.example.json config/config.client.json ; fi
```
https://github.com/libero/reviewer-submission/runs/546000677?check_suite_focus=true

**Comment by diversemix** [comment]
Ah scrap that last comment .... :man_facepalming: ... it is built in `helm/libero-reviewer/templates/configmap-client.yaml`
