### ISSUE TITLE
Issue on Staging

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#737]
```

{"level":50,"time":1586873016178,"pid":1,"hostname":"libero-reviewer--staging-submission-6d5c7b6d65-6vdp5","service":"reviewer-submission","realm":"infra","msg":"Cannot return null for non-nullable field User.id. Error: Cannot return null for non-nullable field User.id.\n    at completeValue (/app/node_modules/graphql/execution/execute.js:560:13)\n    at completeValueCatchingError (/app/node_modules/graphql/execution/execute.js:495:19)\n    at resolveField (/app/node_modules/graphql/execution/execute.js:435:10)\n    at executeFields (/app/node_modules/graphql/execution/execute.js:275:18)\n    at collectAndExecuteSubfields (/app/node_modules/graphql/execution/execute.js:713:10)\n    at completeObjectValue (/app/node_modules/graphql/execution/execute.js:703:10)\n    at completeValue (/app/node_modules/graphql/execution/execute.js:591:12)\n    at completeValue (/app/node_modules/graphql/execution/execute.js:557:21)\n    at /app/node_modules/graphql/execution/execute.js:492:16\n    at processTicksAndRejections (internal/process/task_queues.js:94:5)\n    at async Promise.all (index 0)","v":1}
{"level":50,"time":1586873016205,"pid":1,"hostname":"libero-reviewer--staging-submission-6d5c7b6d65-6vdp5","service":"reviewer-submission","realm":"infra","msg":"Undefined binding(s) detected when compiling SELECT. Undefined column(s): [created_by] query: select \"id\", \"created\", \"updated\", \"created_by\", \"status\", \"meta\", \"cover_letter\" from \"public\".\"manuscript\" where \"created_by\" = ? Error: Undefined binding(s) detected when compiling SELECT. Undefined column(s): [created_by] query: select \"id\", \"created\", \"updated\", \"created_by\", \"status\", \"meta\", \"cover_letter\" from \"public\".\"manuscript\" where \"created_by\" = ?\n    at QueryCompiler_PG.toSQL (/app/node_modules/knex/lib/query/compiler.js:101:13)\n    at Builder.toSQL (/app/node_modules/knex/lib/query/builder.js:77:44)\n    at /app/node_modules/knex/lib/runner.js:30:36\n    at /app/node_modules/knex/lib/runner.js:253:24\n    at tryCatcher (/app/node_modules/bluebird/js/release/util.js:16:23)\n    at Promise._settlePromiseFromHandler (/app/node_modules/bluebird/js/release/promise.js:547:31)\n    at Promise._settlePromise (/app/node_modules/bluebird/js/release/promise.js:604:18)\n    at Promise._settlePromise0 (/app/node_modules/bluebird/js/release/promise.js:649:10)\n    at Promise._settlePromises (/app/node_modules/bluebird/js/release/promise.js:729:18)\n    at _drainQueueStep (/app/node_modules/bluebird/js/release/async.js:93:12)\n    at _drainQueue (/app/node_modules/bluebird/js/release/async.js:86:9)\n    at Async._drainQueues (/app/node_modules/bluebird/js/release/async.js:102:5)\n    at Immediate.Async.drainQueues (/app/node_modules/bluebird/js/release/async.js:15:14)\n    at processImmediate (internal/timers.js:439:21)\n    at process.topLevelDomainCallback (domain.js:130:23)","v":1}
```

**Comment by diversemix** [comment]
This was solved by re-initialising the database
