### ISSUE TITLE
Manuscript upload doesn't work in staging

### ISSUE THREAD

**Issue by erkannt** [libero/reviewer#900]
https://libero-reviewer--staging.elifesciences.org

```
{"level":30,"time":1589554847451,"pid":1,"hostname":"libero-reviewer--stg-submission-f8887557-q8h2h","service":"reviewer-submission","realm":"infra","msg":"Sciencebeam extracting sciencebeam--prod--test-cluster.elifesciences.org","v":1}
{"level":50,"time":1589554847455,"pid":1,"hostname":"libero-reviewer--stg-submission-f8887557-q8h2h","service":"reviewer-submission","realm":"infra","msg":"e87dc2ca-9bf5-41ca-a080-4007d190e734 MANUSCRIPT UPLOAD ERROR {}","v":1}
{"level":50,"time":1589554847478,"pid":1,"hostname":"libero-reviewer--stg-submission-f8887557-q8h2h","service":"reviewer-submission","realm":"infra","msg":"Manuscript upload failed to store file. Error: Manuscript upload failed to store file.\n    at WizardService.saveManuscriptFile (/app/dist/application/wizard/service.js:111:19)\n    at async uploadManuscript (/app/dist/application/wizard/resolvers.js:28:32)","v":1}
```

- manuscript upload gets reported as failure in ui but actually lands in bucket
- supporting file succeeds

**Comment by erkannt** [comment]
submission was pointed at wrong sciencebeam URL. This is now fixed and sciencebeam is receiving the file. But submission throws the same error.

The file is also successfully landing in the s3 bucket.

Error catching  for sciencebeam appears to have an issue: #903 

sciencebeam:
```
DEBUG:urllib3.connectionpool:http://sciencebeam--stg-grobid:8070 "POST /api/processFulltextDocument HTTP/1.1" 200 None
DEBUG:sciencebeam.pipeline_runners.simple_pipeline_runner:executing step (with type "application/tei+xml"): TEI to JATS
DEBUG:sciencebeam.transformers.xslt:xslt_input: <Element {http://www.tei-c.org/ns/1.0}TEI at 0x7f4a6318d408>
DEBUG:sciencebeam.server.blueprints.api:response_content: 359258 (application/vnd.jats+xml)
DEBUG:sciencebeam.server.blueprints.api:output filename: None
INFO:werkzeug:10.0.12.192 - - [18/May/2020 09:45:18] "POST /api/convert?filename=elife-51712-v2.pdf&include=title HTTP/1.1" 200 -
```

submission:
```
{"level":30,"time":1589795098087,"pid":1,"hostname":"libero-reviewer--stg-submission-58478d74d8-lvmp4","service":"reviewer-submission","realm":"infra","msg":"Sciencebeam extracting http://sciencebeam--stg:8075/api/convert","v":1}
{"level":50,"time":1589795118093,"pid":1,"hostname":"libero-reviewer--stg-submission-58478d74d8-lvmp4","service":"reviewer-submission","realm":"infra","msg":"e87dc2ca-9bf5-41ca-a080-4007d190e734 MANUSCRIPT UPLOAD ERROR {}","v":1}
{"level":50,"time":1589795118099,"pid":1,"hostname":"libero-reviewer--stg-submission-58478d74d8-lvmp4","service":"reviewer-submission","realm":"infra","msg":"Manuscript upload failed to store file. Error: Manuscript upload failed to store file.\n    at WizardService.saveManuscriptFile (/app/dist/application/wizard/service.js:111:19)\n    at async uploadManuscript (/app/dist/application/wizard/resolvers.js:28:32)","v":1}
```

**Comment by erkannt** [comment]
https://github.com/libero/reviewer-submission/pull/174 appears to have fixed this issue. But it appears that sciencebeam extraction isn't working.

```
{"level":30,"time":1589796836970,"pid":1,"hostname":"libero-reviewer--stg-submission-c9f755955-2sv7x","service":"reviewer-submission","realm":"infra","msg":"Sciencebeam extracting http://sciencebeam--stg:8075/api/convert","v":1}
{"level":50,"time":1589796856991,"pid":1,"hostname":"libero-reviewer--stg-submission-c9f755955-2sv7x","service":"reviewer-submission","realm":"infra","msg":"No response response recieved for
request","v":1}
```

```
INFO:werkzeug:10.0.12.106 - - [18/May/2020 10:13:55] "GET /api/convert HTTP/1.1" 200 -
DEBUG:sciencebeam.server.blueprints.api:checking max requests (requests: 0, max: 10)
DEBUG:sciencebeam.server.blueprints.api:processing file: elife-51712-v2.pdf (3349495 bytes, type "application/pdf")
DEBUG:sciencebeam.pipeline_runners.simple_pipeline_runner:skipping step (type "application/pdf" not supported): DOC to .pdf
DEBUG:sciencebeam.pipeline_runners.simple_pipeline_runner:executing step (with type "application/pdf"): Convert to TEI
INFO:sciencebeam.transformers.grobid_service:processing: elife-51712-v2.pdf (3349495) - http://sciencebeam--stg-grobid:8070/api/processFulltextDocument
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): sciencebeam--stg-grobid:8070
INFO:werkzeug:10.0.12.106 - - [18/May/2020 10:13:58] "GET /api/convert HTTP/1.1" 200 -
```
