### ISSUE TITLE
Implement browser testing against Edge and Safari at x point in pipeline

### ISSUE THREAD

**Issue by Cooryd** [libero/reviewer#921]
x to be defined as part of #919

**Comment by erkannt** [comment]
- Edge18 gets stuck in loop, fails to even close down the browserstack session
- Safari appears to be flaky, maybe a [ports issue](https://www.browserstack.com/question/664)

**Comment by erkannt** [comment]
```
   (/home/runner/work/reviewer-client/reviewer-client/tests/page-objects/NavigationPane.ts:21:47)
         at <anonymous>

   (/home/runner/work/reviewer-client/reviewer-client/tests/page-objects/NavigationPane.ts:8:71)
         at __awaiter

   (/home/runner/work/reviewer-client/reviewer-client/tests/page-objects/NavigationPane.ts:4:12)
         at NavigationPane.assertOnPageAuthenticated

   (/home/runner/work/reviewer-client/reviewer-client/tests/page-objects/NavigationPane.ts:33:16)
         at <anonymous>

   (/home/runner/work/reviewer-client/reviewer-client/tests/browser-tests/Login.browser.ts:37:26)
         at fulfilled
      (/home/runner/work/reviewer-client/reviewer-client/tests/browser-tests/Login.browser.ts:5:58)



 1/3 failed (29s)
```

**Comment by erkannt** [comment]
```
2020-06-01T09:23:12.4335367Z yarn testcafe 'browserstack:safari@11.1:OS X High Sierra' 'tests/**/*.browser.ts'
2020-06-01T09:23:12.5752993Z yarn run v1.22.4
2020-06-01T09:23:13.1887197Z $ /home/runner/work/reviewer-client/reviewer-client/node_modules/.bin/testcafe 'browserstack:safari@11.1:OS X High Sierra' 'tests/**/*.browser.ts'
2020-06-01T09:23:28.0355557Z  Running tests in:
2020-06-01T09:23:28.0360110Z  - Safari 11.1.2 / macOS 10.13.6
2020-06-01T09:23:28.0360900Z  (https://automate.browserstack.com/builds/17f7dd6d1f117756df5a05c657254c49b8c9aa38/sessions/6e18373ddb517224be0dd72c175735f89fcfb4cd)
2020-06-01T09:23:28.0361262Z 
2020-06-01T09:23:28.0361592Z  Getting Started
2020-06-01T09:23:43.8448390Z  ✓ assert nav bar
2020-06-01T09:23:48.4574060Z  ✓ My first test
2020-06-01T09:23:56.8325534Z  ✖ Happy path
2020-06-01T09:23:56.8327599Z 
2020-06-01T09:23:56.8424911Z    1) A JavaScript error occurred on "http://localhost:9000/".
2020-06-01T09:23:56.8425469Z       Repeat test actions in the browser and check the console for errors.
2020-06-01T09:23:56.8425842Z       If you see this error, it means that the tested website caused it.
2020-06-01T09:23:56.8426190Z       You can fix it or disable tracking JavaScript errors in TestCafe. To
2020-06-01T09:23:56.8426852Z       do the latter, enable the "--skip-js-errors" option.
2020-06-01T09:23:56.8427275Z       If this error does not occur, please write a new issue at:
2020-06-01T09:23:56.8427651Z 
2020-06-01T09:23:56.8428614Z    "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".
2020-06-01T09:23:56.8428985Z 
2020-06-01T09:23:56.8429301Z       JavaScript error details:
2020-06-01T09:23:56.8429851Z       undefined is not an object (evaluating '_.getSubmissions'):
2020-06-01T09:23:56.8430268Z       http://localhost:9000/main.211ad25a74be475f0495.js:2:13385
2020-06-01T09:23:56.8430877Z       Ni@http://localhost:9000/npm.react-dom.f8de6058e12e839bc0a2.js:10:56557
2020-06-01T09:23:56.8431507Z       aa@http://localhost:9000/npm.react-dom.f8de6058e12e839bc0a2.js:10:63582
2020-06-01T09:23:56.8432119Z       Eo@http://localhost:9000/npm.react-dom.f8de6058e12e839bc0a2.js:10:85045
2020-06-01T09:23:56.8432736Z       wo@http://localhost:9000/npm.react-dom.f8de6058e12e839bc0a2.js:10:82077
2020-06-01T09:23:56.8433104Z       wo@[native code]
2020-06-01T09:23:56.8433652Z       ho@http://localhost:9000/npm.react-dom.f8de6058e12e839bc0a2.js:10:80669
2020-06-01T09:23:56.8434016Z       ho@[native code]
2020-06-01T09:23:56.8434810Z       http://localhost:9000/npm.react-dom.f8de6058e12e839bc0a2.js:10:42963
2020-06-01T09:23:56.8435111Z 
2020-06-01T09:23:56.8435507Z    unstable_runWithPriority@http://localhost:9000/npm.scheduler.4613856f0c31095241d0.js:10:4153
2020-06-01T09:23:56.8436094Z       vl@http://localhost:9000/npm.react-dom.f8de6058e12e839bc0a2.js:10:42901
2020-06-01T09:23:56.8436708Z       gl@http://localhost:9000/npm.react-dom.f8de6058e12e839bc0a2.js:10:42836
2020-06-01T09:23:56.8437316Z       so@http://localhost:9000/npm.react-dom.f8de6058e12e839bc0a2.js:10:79663
2020-06-01T09:23:56.8437928Z       Wi@http://localhost:9000/npm.react-dom.f8de6058e12e839bc0a2.js:10:59675
2020-06-01T09:23:56.8438289Z       Wi@[native code]
2020-06-01T09:23:56.8438642Z       error@http://localhost:9000/npm.apollo.f445f0d2608a313a1230.js:2:7580
2020-06-01T09:23:56.8438881Z 
2020-06-01T09:23:56.8439432Z    _@http://localhost:9000/npm.zen-observable.e8b9f13f4f09887f8413.js:2:1588
2020-06-01T09:23:56.8439747Z 
2020-06-01T09:23:56.8440309Z    m@http://localhost:9000/npm.zen-observable.e8b9f13f4f09887f8413.js:2:2058
2020-06-01T09:23:56.8440614Z 
2020-06-01T09:23:56.8441179Z    value@http://localhost:9000/npm.zen-observable.e8b9f13f4f09887f8413.js:2:2675
2020-06-01T09:23:56.8441591Z       n@http://10.1.0.4:32937/hammerhead.js:15:22017
2020-06-01T09:23:56.8441969Z       value@http://10.1.0.4:32937/hammerhead.js:6:15494
2020-06-01T09:23:56.8442483Z       forEach@[native code]
2020-06-01T09:23:56.8442925Z 
2020-06-01T09:23:56.8443504Z    Q@http://localhost:9000/npm.apollo-client.8cad57501f2478c897a0.js:2:8762
2020-06-01T09:23:56.8443815Z 
2020-06-01T09:23:56.8444400Z    a@http://localhost:9000/npm.apollo-client.8cad57501f2478c897a0.js:2:7831
2020-06-01T09:23:56.8444847Z       n@http://10.1.0.4:32937/hammerhead.js:15:22017
2020-06-01T09:23:56.8445231Z       value@http://10.1.0.4:32937/hammerhead.js:6:15494
2020-06-01T09:23:56.8445479Z 
2020-06-01T09:23:56.8446216Z    n@http://localhost:9000/npm.apollo-client.8cad57501f2478c897a0.js:2:22463
2020-06-01T09:23:56.8446844Z       http://localhost:9000/npm.apollo-client.8cad57501f2478c897a0.js:2:29143
2020-06-01T09:23:56.8447218Z       forEach@[native code]
2020-06-01T09:23:56.8447768Z       http://localhost:9000/npm.apollo-client.8cad57501f2478c897a0.js:2:29125
2020-06-01T09:23:56.8448136Z       forEach@[native code]
2020-06-01T09:23:56.8448371Z 
2020-06-01T09:23:56.8448934Z    broadcastQueries@http://localhost:9000/npm.apollo-client.8cad57501f2478c897a0.js:2:29075
2020-06-01T09:23:56.8449541Z       http://localhost:9000/npm.apollo-client.8cad57501f2478c897a0.js:2:21620
2020-06-01T09:23:56.8449838Z 
2020-06-01T09:23:56.8450724Z    nrWrapper@http://localhost:9000/login#eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJlNGI5MTM5Mi01MmQ1LTRjMDQtODM4YS05YTUwMDZkNDZkNzMiLCJpc3MiOiJjb250aW51dW0tYWRhcHRvciIsImlzc3VlciI6ImxpYmVybyIsImlhdCI6MTU5MTAwMzQzMiwiZXhwIjoxNTkxMDg5ODMyfQ.x185Xu9o1g-XHe5UesgIweu-YV9tfaF3JAe6Tx3Qy6s:2:19251
2020-06-01T09:23:56.8451150Z       promiseReactionJob@[native code]
2020-06-01T09:23:56.8451498Z 
2020-06-01T09:23:56.8451954Z       Browser: Safari 11.1.2 / macOS 10.13.6
2020-06-01T09:23:56.8453163Z       (https://automate.browserstack.com/builds/17f7dd6d1f117756df5a05c657254c49b8c9aa38/sessions/6e18373ddb517224be0dd72c175735f89fcfb4cd)
2020-06-01T09:23:56.8453438Z 
2020-06-01T09:23:56.8453659Z 
2020-06-01T09:23:56.8567517Z    2) AssertionError: expected false to be truthy
2020-06-01T09:23:56.8567911Z 
2020-06-01T09:23:56.8568306Z       Browser: Safari 11.1.2 / macOS 10.13.6
2020-06-01T09:23:56.8568584Z 
2020-06-01T09:23:56.8569045Z    (https://automate.browserstack.com/builds/17f7dd6d1f117756df5a05c657254c49b8c9aa38/sessions/6e18373ddb517224be0dd72c175735f89fcfb4cd)
2020-06-01T09:23:56.8569369Z 
2020-06-01T09:23:56.8569718Z          16 |        await
2020-06-01T09:23:56.8570081Z       t.expect(this.burgerMenuButton.visible).notOk();
2020-06-01T09:23:56.8570457Z          17 |        await t.expect(this.profileDropdown.visible).notOk();
2020-06-01T09:23:56.8570831Z          18 |    }
2020-06-01T09:23:56.8571405Z          19 |
2020-06-01T09:23:56.8571797Z          20 |    public async assertOnPageAuthenticated(): Promise<void> {
2020-06-01T09:23:56.8572178Z        > 21 |        await t.expect(this.iconLink.visible).ok();
2020-06-01T09:23:56.8572568Z          22 |        await t.expect(this.menu.visible).ok();
2020-06-01T09:23:56.8572944Z          23 |        await t.expect(this.profileDropdown.visible).ok();
2020-06-01T09:23:56.8573367Z          24 |        // should only appear in responsive mode
2020-06-01T09:23:56.8573760Z          25 |        await
2020-06-01T09:23:56.8574120Z       t.expect(this.burgerMenuContainer.visible).notOk();
2020-06-01T09:23:56.8574463Z          26 |        await
2020-06-01T09:23:56.8574836Z       t.expect(this.burgerMenuContent.visible).notOk();
2020-06-01T09:23:56.8575113Z 
2020-06-01T09:23:56.8575444Z          at NavigationPane.<anonymous>
2020-06-01T09:23:56.8575657Z 
2020-06-01T09:23:56.8576371Z    (/home/runner/work/reviewer-client/reviewer-client/tests/page-objects/NavigationPane.ts:21:47)
2020-06-01T09:23:56.8576923Z          at <anonymous>
2020-06-01T09:23:56.8577168Z 
2020-06-01T09:23:56.8577795Z    (/home/runner/work/reviewer-client/reviewer-client/tests/page-objects/NavigationPane.ts:8:71)
2020-06-01T09:23:56.8578212Z          at __awaiter
2020-06-01T09:23:56.8578509Z 
2020-06-01T09:23:56.8579113Z    (/home/runner/work/reviewer-client/reviewer-client/tests/page-objects/NavigationPane.ts:4:12)
2020-06-01T09:23:56.8579535Z          at NavigationPane.assertOnPageAuthenticated
2020-06-01T09:23:56.8579760Z 
2020-06-01T09:23:56.8580354Z    (/home/runner/work/reviewer-client/reviewer-client/tests/page-objects/NavigationPane.ts:33:16)
2020-06-01T09:23:56.8580849Z          at <anonymous>
2020-06-01T09:23:56.8581087Z 
2020-06-01T09:23:56.8581688Z    (/home/runner/work/reviewer-client/reviewer-client/tests/browser-tests/Login.browser.ts:37:26)
2020-06-01T09:23:56.8582317Z          at fulfilled
2020-06-01T09:23:56.8583019Z       (/home/runner/work/reviewer-client/reviewer-client/tests/browser-tests/Login.browser.ts:5:58)
2020-06-01T09:23:56.8583399Z 
2020-06-01T09:23:56.8583671Z 
2020-06-01T09:23:57.0471292Z 
2020-06-01T09:23:57.0473137Z  1/3 failed (29s)
```

**Comment by erkannt** [comment]
Matrix job maybe more flaky than serial run?
https://github.com/libero/reviewer-client/runs/727093776?check_suite_focus=true
https://automate.browserstack.com/dashboard/v2/builds/e4009ecbd55af6556ad287d5f20e4f83e59228b0

**Comment by erkannt** [comment]
More errors from other browsers that have previously passed:

https://github.com/libero/reviewer-client/runs/727128109?check_suite_focus=true
https://automate.browserstack.com/dashboard/v2/builds/0dd2957faf3138f9d8365255fabb2a081d54a792/sessions/3c50ba189d143185f7efddb6eb5a7b4f9fd43df8

**Comment by erkannt** [comment]
Safari network connection lost error.

https://github.com/libero/reviewer/issues/921

```
2020-06-01T12:33:17.2762024Z $ /home/runner/work/reviewer-client/reviewer-client/node_modules/.bin/testcafe 'browserstack:safari@11.1:OS X High Sierra' 'tests/**/*.browser.ts'
2020-06-01T12:33:40.1965864Z  Running tests in:
2020-06-01T12:33:40.1968950Z  - Safari 11.1.2 / macOS 10.13.6
2020-06-01T12:33:40.1969665Z  (https://automate.browserstack.com/builds/cea112041cd5d9be324379485e28ec9c670c3db6/sessions/58a302db1b14d65df833c504d3697118faec99a7)
2020-06-01T12:33:40.1970010Z 
2020-06-01T12:33:40.1970388Z  Getting Started
2020-06-01T12:34:31.0939821Z  ✓ assert nav bar
2020-06-01T12:34:50.0539632Z  ✓ My first test
2020-06-01T12:35:48.3525157Z  ✖ Happy path
2020-06-01T12:35:48.3525968Z 
2020-06-01T12:35:48.3736650Z    1) A JavaScript error occurred on
2020-06-01T12:35:48.3737154Z 
2020-06-01T12:35:48.3738158Z    "http://localhost:9000/submit/937d643b-9bbd-42e7-9445-78b8e417ee68/details".
2020-06-01T12:35:48.3738628Z       Repeat test actions in the browser and check the console for errors.
2020-06-01T12:35:48.3739472Z       If you see this error, it means that the tested website caused it.
2020-06-01T12:35:48.3739880Z       You can fix it or disable tracking JavaScript errors in TestCafe. To
2020-06-01T12:35:48.3740506Z       do the latter, enable the "--skip-js-errors" option.
2020-06-01T12:35:48.3740943Z       If this error does not occur, please write a new issue at:
2020-06-01T12:35:48.3741203Z 
2020-06-01T12:35:48.3741798Z    "https://github.com/DevExpress/testcafe/issues/new?template=bug-report.md".
2020-06-01T12:35:48.3742108Z 
2020-06-01T12:35:48.3742450Z       JavaScript error details:
2020-06-01T12:35:48.3742817Z       Network error: The network connection was lost.:
2020-06-01T12:35:48.3743067Z 
2020-06-01T12:35:48.3743661Z    t@http://localhost:9000/npm.apollo-client.8cad57501f2478c897a0.js:2:1156
2020-06-01T12:35:48.3743970Z 
2020-06-01T12:35:48.3744588Z    error@http://localhost:9000/npm.apollo-client.8cad57501f2478c897a0.js:2:19487
2020-06-01T12:35:48.3744909Z 
2020-06-01T12:35:48.3745498Z    _@http://localhost:9000/npm.zen-observable.e8b9f13f4f09887f8413.js:2:1588
2020-06-01T12:35:48.3745786Z 
2020-06-01T12:35:48.3746421Z    m@http://localhost:9000/npm.zen-observable.e8b9f13f4f09887f8413.js:2:2058
2020-06-01T12:35:48.3746733Z 
2020-06-01T12:35:48.3747325Z    value@http://localhost:9000/npm.zen-observable.e8b9f13f4f09887f8413.js:2:2675
2020-06-01T12:35:48.3747713Z       forEach@[native code]
2020-06-01T12:35:48.3747971Z 
2020-06-01T12:35:48.3748559Z    error@http://localhost:9000/npm.apollo-client.8cad57501f2478c897a0.js:2:16671
2020-06-01T12:35:48.3748847Z 
2020-06-01T12:35:48.3749430Z    _@http://localhost:9000/npm.zen-observable.e8b9f13f4f09887f8413.js:2:1588
2020-06-01T12:35:48.3749879Z 
2020-06-01T12:35:48.3750470Z    m@http://localhost:9000/npm.zen-observable.e8b9f13f4f09887f8413.js:2:2058
2020-06-01T12:35:48.3750759Z 
2020-06-01T12:35:48.3751347Z    value@http://localhost:9000/npm.zen-observable.e8b9f13f4f09887f8413.js:2:2675
2020-06-01T12:35:48.3751662Z 
2020-06-01T12:35:48.3752253Z    error@http://localhost:9000/npm.apollo-link-error.321052fd9c036fb47ec7.js:2:711
2020-06-01T12:35:48.3752560Z 
2020-06-01T12:35:48.3753144Z    _@http://localhost:9000/npm.zen-observable.e8b9f13f4f09887f8413.js:2:1588
2020-06-01T12:35:48.3753623Z 
2020-06-01T12:35:48.3754245Z    m@http://localhost:9000/npm.zen-observable.e8b9f13f4f09887f8413.js:2:2058
2020-06-01T12:35:48.3754550Z 
2020-06-01T12:35:48.3755137Z    value@http://localhost:9000/npm.zen-observable.e8b9f13f4f09887f8413.js:2:2675
2020-06-01T12:35:48.3755517Z       value@[native code]
2020-06-01T12:35:48.3755777Z 
2020-06-01T12:35:48.3756357Z    _@http://localhost:9000/npm.zen-observable.e8b9f13f4f09887f8413.js:2:1588
2020-06-01T12:35:48.3756644Z 
2020-06-01T12:35:48.3757398Z    m@http://localhost:9000/npm.zen-observable.e8b9f13f4f09887f8413.js:2:2058
2020-06-01T12:35:48.3757725Z 
2020-06-01T12:35:48.3758360Z    value@http://localhost:9000/npm.zen-observable.e8b9f13f4f09887f8413.js:2:2675
2020-06-01T12:35:48.3759260Z 
2020-06-01T12:35:48.3760031Z    http://localhost:9000/npm.apollo-upload-client.b62108459f83f0251420.js:2:1583
2020-06-01T12:35:48.3760387Z       promiseReactionJob@[native code]
2020-06-01T12:35:48.3760596Z 
2020-06-01T12:35:48.3760906Z       Browser: Safari 11.1.2 / macOS 10.13.6
2020-06-01T12:35:48.3761101Z 
2020-06-01T12:35:48.3761545Z    (https://automate.browserstack.com/builds/cea112041cd5d9be324379485e28ec9c670c3db6/sessions/58a302db1b14d65df833c504d3697118faec99a7)
2020-06-01T12:35:48.3762196Z 
2020-06-01T12:35:48.3762547Z          110 |        await this.secondCosubmissionTitleInput.value;
2020-06-01T12:35:48.3762846Z          111 |    }
2020-06-01T12:35:48.3763126Z          112 |
2020-06-01T12:35:48.3763452Z          113 |    public async next(): Promise<void> {
2020-06-01T12:35:48.3763793Z          114 |        await t.expect(this.nextButton.visible).ok();
2020-06-01T12:35:48.3764134Z        > 115 |        await t.click(this.nextButton);
2020-06-01T12:35:48.3764563Z          116 |    }
2020-06-01T12:35:48.3764840Z          117 |
2020-06-01T12:35:48.3765161Z          118 |    public async back(): Promise<void> {
2020-06-01T12:35:48.3765524Z          119 |        await t.expect(this.backButton.visible).ok();
2020-06-01T12:35:48.3765861Z          120 |        await t.click(this.backButton);
2020-06-01T12:35:48.3766073Z 
2020-06-01T12:35:48.3766363Z          at DetailsPage.<anonymous>
2020-06-01T12:35:48.3766556Z 
2020-06-01T12:35:48.3767171Z    (/home/runner/work/reviewer-client/reviewer-client/tests/page-objects/DetailsPage.ts:115:17)
2020-06-01T12:35:48.3767511Z          at fulfilled
2020-06-01T12:35:48.3768143Z       (/home/runner/work/reviewer-client/reviewer-client/tests/page-objects/DetailsPage.ts:5:58)
2020-06-01T12:35:48.3768366Z 
2020-06-01T12:35:48.3768562Z 
2020-06-01T12:35:48.6257988Z 
2020-06-01T12:35:48.6258893Z  1/3 failed (2m 08s)
```

**Comment by erkannt** [comment]
Navbar test fails due to iconLink not being visible. But looking at the replay I can see the icon link being rendered:

https://automate.browserstack.com/dashboard/v2/builds/c98147099e69da7deaed483044cd65322d63c2cc/sessions/2ea28594269c618ba2e05335b24d8fe64618a9ad

```
$ /home/hff/code/libero/reviewer-client/node_modules/.bin/testcafe 'browserstack:firefox@76.0:Windows 10' 'tests/**/*.browser.ts'
 Running tests in:
 - Firefox 76.0 / Windows 10
 (https://automate.browserstack.com/builds/c98147099e69da7deaed483044cd65322d63c2cc/sessions/2ea28594269c618ba2e05335b24d8fe64618a9ad)

 Getting Started
 ✖ assert nav bar

   1) AssertionError: expected false to be truthy

      Browser: Firefox 76.0 / Windows 10
      (https://automate.browserstack.com/builds/c98147099e69da7deaed483044cd65322d63c2cc/sessions/2ea28594269c618ba2e05335b24d8fe64618a9ad)

         16 |        await t.expect(this.burgerMenuButton.visible).notOk();
         17 |        await t.expect(this.profileDropdown.visible).notOk();
         18 |    }
         19 |
         20 |    public async assertOnPageAuthenticated(): Promise<void> {
       > 21 |        await t.expect(this.iconLink.visible).ok();
         22 |        await t.expect(this.menu.visible).ok();
         23 |        await t.expect(this.profileDropdown.visible).ok();
         24 |        // should only appear in responsive mode
         25 |        await t.expect(this.burgerMenuContainer.visible).notOk();
         26 |        await t.expect(this.burgerMenuContent.visible).notOk();

         at NavigationPane.<anonymous> (/home/hff/code/libero/reviewer-client/tests/page-objects/NavigationPane.ts:21:47)
         at <anonymous> (/home/hff/code/libero/reviewer-client/tests/page-objects/NavigationPane.ts:8:71)
         at __awaiter (/home/hff/code/libero/reviewer-client/tests/page-objects/NavigationPane.ts:4:12)
         at NavigationPane.assertOnPageAuthenticated (/home/hff/code/libero/reviewer-client/tests/page-objects/NavigationPane.ts:33:16)
         at <anonymous> (/home/hff/code/libero/reviewer-client/tests/browser-tests/Login.browser.ts:12:26)
         at fulfilled (/home/hff/code/libero/reviewer-client/tests/browser-tests/Login.browser.ts:5:58)


 ✓ My first test
 ✓ Happy path


 1/3 failed (1m 24s)

```

**Comment by erkannt** [comment]
After switching to saucelabs we still get errors. So there appears to either be an issue with testcafe and/or our code. All saucelab errors are collected [here](https://github.com/libero/reviewer/issues/988#issuecomment-638824883). Mostly Safari but also one Edge83 and one Chrome.

**Comment by erkannt** [comment]
After the removal of PeoplePicker-search (https://github.com/libero/reviewer-client/pull/271) browserstack fails for Firefox and Safari 13.1.

https://automate.browserstack.com/dashboard/v2/builds/53947f69b043c9f291accfe780d81e5377d6eca4
