### ISSUE TITLE
The user role is not set correctly in containerized browser tests

### ISSUE THREAD

**Issue by diversemix** [libero/reviewer#938]
See https://github.com/libero/reviewer/pull/936

**Comment by diversemix** [comment]
This can be reproduced locally. I did have an issue with a stale token

**Comment by diversemix** [comment]
On login continuum-adaptor correctly returns the user:
```
{"id":"ewwboc7m","type":{"id":"author","label":"Author"},"name":{"preferred":"Tamlyn Rhodes","index":"Rhodes, Tamlyn"}}
```

**Comment by diversemix** [comment]
Checked in submission that the value got back from the adaptor is also correct:

```
User role is: author
```

**Comment by diversemix** [comment]
Now its failing on another test - file upload - suspect its resource limitation on the test VM - we need to understand more about what is happening

**Comment by diversemix** [comment]
ok - the test work locally - take 3m25s ... this is compared with 3m37s in the pipeline, where they fail.

**Comment by diversemix** [comment]
Searching the logs reveals:
```
 submission_1         | {"level":50,"time":1590138763728,"pid":1,"hostname":"b4b2fdf0b097","service":"reviewer-submission","realm":"infra","msg":"d4d10e65-ca64-4972-acf2-246d59f6e04e MANUSCRIPT UPLOAD ERROR {\"message\":\"The specified bucket does not exist\",\"code\":\"NoSuchBucket\",\"region\":null,\"time\":\"2020-05-22T09:12:43.727Z\",\"requestId\":\"16114EC7DB196C72\",\"statusCode\":404,\"retryable\":false,\"retryDelay\":48.00922804682972}","v":1}
submission_1         | {"level":50,"time":1590138763734,"pid":1,"hostname":"b4b2fdf0b097","service":"reviewer-submission","realm":"infra","msg":"Manuscript upload failed to store file. Error: Manuscript upload failed to store file.\n    at WizardService.saveManuscriptFile (/app/dist/application/wizard/service.js:111:19)\n    at async uploadManuscript (/app/dist/application/wizard/resolvers.js:28:32)","v":1}
```
